# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'PIOFlasher.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setWindowModality(QtCore.Qt.NonModal)
        MainWindow.resize(380, 420)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(380, 420))
        MainWindow.setMaximumSize(QtCore.QSize(380, 420))
        MainWindow.setAcceptDrops(True)
        MainWindow.setStyleSheet("QWidget {\n"
"    background-color: rgb(30, 30, 30);\n"
"    color: rgb(255, 255, 255);\n"
"    font: 12pt \\\"Arial Rounded MT Bold\\\";\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(60, 60, 60);\n"
"}\n"
"\n"
"QTextEdit{\n"
"    border: 1px solid rgb(60, 75, 140);\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 12px;\n"
"}\n"
"\n"
"QLineEdit{\n"
"    border: 1px solid rgb(60, 75, 140);\n"
"    color: rgb(255, 255, 255);\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: rgb(40, 40, 40);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 1px solid rgb(60, 75, 140);\n"
"    border-radius: 5px;\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"QToolButton {\n"
"    background-color: rgb(40, 40, 40);\n"
"    color: rgb(255, 255, 255);\n"
"    border: 1px solid rgb(60, 75, 140);\n"
"    border-radius: 2px;\n"
"    font-size: 16px;\n"
"}\n"
"\n"
"QToolButton:hover {\n"
"    background-color: rgb(60, 60, 60);\n"
"}\n"
"\n"
"QProgressBar {\n"
"    border: 2px solid #8f8f91;\n"
"    border-radius: 2px;\n"
"    background-color: #54565e;\n"
"}")
        MainWindow.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 70, 341, 321))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.conOut = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.conOut.setReadOnly(True)
        self.conOut.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.conOut)
        self.Button_flash = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Button_flash.setObjectName("Button_flash")
        self.verticalLayout.addWidget(self.Button_flash)
        self.Button_uploadfs = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Button_uploadfs.setObjectName("Button_uploadfs")
        self.verticalLayout.addWidget(self.Button_uploadfs)
        self.Button_erase_flash = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.Button_erase_flash.setObjectName("Button_erase_flash")
        self.verticalLayout.addWidget(self.Button_erase_flash)
        self.progressBar = QtWidgets.QProgressBar(self.verticalLayoutWidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setTextVisible(False)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(20, 30, 341, 27))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit.setInputMask("")
        self.lineEdit.setText("")
        self.lineEdit.setMaxLength(32767)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.toolButton = QtWidgets.QToolButton(self.layoutWidget)
        self.toolButton.setObjectName("toolButton")
        self.horizontalLayout.addWidget(self.toolButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PIO Flasher"))
        self.conOut.setPlaceholderText(_translate("MainWindow", "CONSOLE OUTPUT"))
        self.Button_flash.setText(_translate("MainWindow", "Flash! 🡺"))
        self.Button_uploadfs.setText(_translate("MainWindow", "Upload data in board FS 🡺"))
        self.Button_erase_flash.setText(_translate("MainWindow", "Erase flash [X]"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Path to PIO project folder"))
        self.toolButton.setText(_translate("MainWindow", "..."))
